export const indianFirstNames = [
    "Aarav", "Advik", "Akshay", "Aarush", "Arjun", "Ayush", "Ananya", "Anaya",    "Aadhya", "Aaradhya","Bhavya", "Chirag", "Dev", "Divya", "Esha", "Ekta", "Gaurav", "Geeta", "Harsh", "Ishan","Ishaan", "Jai", "Karan", "Krish", "Kiaan", "Lavanya", "Manan", "Meera", "Nisha", "Neha","Om", "Prisha", "Priya", "Riya", "Reeva", "Saanvi", "Sameer", "Sanaya", "Shiv", "Sahil","Tanisha", "Trisha", "Uday", "Varun", "Ved", "Veer", "Yash", "Yuvraj", "Zara", "Zoya","Aanya", "Aryan", "Aaradhana", "Ankit", "Aadi", "Avani", "Armaan", "Aisha", "Ansh", "Anvita","Bhumika", "Bhuvan", "Chetan", "Chaitanya", "Disha", "Diya", "Eshika", "Eklavya", "Gautam", "Gunjan","Hritik", "Hema", "Ishika", "Inaya", "Jyoti", "Jahan", "Kavya", "Kriti", "Kartik", "Laksh","Lavanya", "Mohit", "Muskaan", "Naman", "Nirav", "Navya", "Omkar", "Pranav", "Preeti", "Parth","Riyaan", "Rhea", "Surya", "Sakshi", "Siddharth", "Tanya", "Tanay", "Tanvi", "Vansh", "Vaishnavi","Aarohi", "Amit", "Asha", "Anika", "Anjali", "Arnav", "Amitabh", "Babita", "Bharat", "Bhaskar","Charan", "Chandni", "Deepak", "Dhruv", "Diksha", "Ekta", "Farhan", "Ganesh", "Gopal", "Hari","Hema", "Indira", "Ishita", "Jayesh", "Juhi", "Kapil", "Kiran", "Kumar", "Kavita", "Leela","Madhav", "Mala", "Manisha", "Nandini", "Neeraj", "Nikita", "Ojas", "Pankaj", "Pooja", "Pradeep","Pranay", "Pramod", "Radha", "Rajesh", "Ravi", "Rahul", "Rekha", "Rohit", "Rupali", "Sarita","Shankar", "Shashi", "Shikha", "Shiva", "Smita", "Suresh", "Tarun", "Trupti", "Usha", "Vijay","Vinod", "Vikram", "Vineet", "Vivek", "Yogesh", "Yashwant", "Zubin", "Zainab", "Aarti", "Alok","Anushka", "Arun", "Anand", "Avinash", "Bhavesh", "Chitra", "Deepika", "Dinesh", "Divakar", "Eshaan","Firoz", "Ganesh", "Geeta", "Harsha", "Hemant", "Inder", "Irfan", "Jagdish", "Jaspreet", "Kamal","Kavita", "Kishan", "Komal", "Kuldeep", "Madhu", "Mukesh", "Naveen", "Nehal", "Niraj", "Nisha","Padmini", "Pranjal", "Praveen", "Rajendra", "Rahul", "Ramesh", "Ranjeet", "Roshan", "Sachin", "Sanjay", "Santosh", "Sapna", "Satish", "Shalini", "Shashi", "Shubham", "Sonal", "Sunil", "Sushil", "Tejas", "Umesh", "Upendra", "Vaibhav", "Vikas", "Vikram", "Vimal", "Vishal", "Vivek", "Yogesh", "Yogita"
    ];
    
export const indianLastNames = [
        "Agarwal", "Ahluwalia", "Ahuja", "Arora", "Bajaj", "Batra", "Chopra", "Dewan", "Gupta", "Jain","Jha", "Kapoor", "Khanna", "Kumar", "Mahajan", "Malhotra", "Mehra", "Mittal", "Nanda", "Patel","Rajput", "Sethi", "Sharma", "Singh", "Taneja", "Thakur", "Verma", "Bhandari", "Bhatia", "Chauhan", "Das", "Dhillon", "Dutta", "Gandhi", "Ganguly", "Goswami", "Iyer", "Kaul", "Khatri", "Lal", "Mishra", "Nair", "Nath", "Pandey", "Rana", "Reddy", "Sarin", "Saxena", "Shah", "Shroff","Srivastava", "Tiwari", "Trivedi", "Vohra", "Yadav", "Anand", "Bakshi", "Biswas", "Chadda", "Chandra", "Chopra", "Dewan", "Ganesh", "Gill", "Gokhale", "Iyengar", "Iyer", "Joshi", "Kaul", "Kishore","Lal", "Malhotra", "Mathur", "Mehta", "Mohan", "Naidu", "Nair", "Narayan", "Padmanabhan", "Pandit","Raj", "Ram", "Ranganathan", "Rao", "Rastogi", "Roy", "Sarin", "Sen", "SenGupta", "Shankar","Sharma", "Shetty", "Singhania", "Sinha", "Subramanian", "Sundaram", "Suri", "Talwar", "Trivedi","Venkatesh", "Vijayan", "Viswanathan", "Yadav", "Achari", "Adiga", "Ahuja", "Aithal", "Anand", "Balakrishnan","Balasubramanian", "Bhat", "Bhatnagar", "Chandrasekhar", "Chopra", "Dhawan", "Dutta", "Ganapathy", "Ghosh","Goswami", "Gupta", "Hariharan", "Iyer", "Iyengar", "Jain", "Jayaraman", "Kannan", "Krishnan", "Lal","Majumdar", "Menon", "Mishra", "Mukherjee", "Murthy", "Narayan", "Natarajan", "Padmanabhan", "Pal", "Panicker","Patil", "Pillai", "Prasad", "Raghavan", "Raju", "Raman", "Rangan", "Ranganathan", "Rao", "Ravi","Reddy", "Saha", "Saraswathi", "Sarcar", "Sarkar", "Sathe", "Sen", "Shankar", "Sharma", "Shastri","Shukla", "Sinha", "Srinivasan", "Subramanian", "Sundaram", "Swaminathan", "Thakur", "Thomas", "Trivedi","Varma", "Venkataraman", "Venkatesh", "Venugopal", "Vyas", "Yadav", "Yadava"
    ];
export const allCharacters = [
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z','A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z','0', '1', '2', '3', '4', '5', '6', '7', '8', '9','@', '#', '$', '%', '&', '?'
    ];
    